name: Build Docker and Singularity

on:
  push:
    branches:
      - main

jobs:
  Build_Docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Clone Docker
      with:
        repository: scilus/docker-dmriqc
        ref: master
    - uses: mr-smithers-excellent/docker-build-push@v3.1
      name: Docker Build & Push
      with:
        image: scilus/dmriqc_flow
        tag: latest
        dockerfile: /home/runner/work/dmriqcpy/docker-dmriqc/Dockerfile
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  Build_Singularity:
    needs: Build_Docker

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Clone Singularity
      with:
        repository: GuillaumeTh/singularity-dmriqc
        ref: master
    - name: Install and build Singularity
      run: |
        sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
        sudo apt-key adv --recv-keys --keyserver pool.sks-keyservers.net 2649A5A9 || { sudo wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -; }
        sudo apt-get update
        sudo apt-get install -y singularity-container
        mkdir singularity_dmriqc_build
        curr_date=$(date "+%Y%m%d")
        sudo singularity build singularity_dmriqc_build/singularity_dmriqc_${curr_date}_${GITHUB_SHA}.img /home/runner/work/dmriqcpy/singularity-dmriqc/singularity_dmriqcpy.def

    - uses: actions/upload-artifact@v1
      name: Push Singularity
      with:
        name: singularity_dmriqc
        path: singularity_dmriqc_build/
